# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[so]
  languageCode = "so"
  contentDir = "content/so"
  languageName = "Soomaali"
  title = "Badbaad"
  weight = 1
  [so.params]
    description = "Madasha caafimaadka guud"

[en]
  languageCode = "en-us"
  contentDir = "content/en"
  languageName = "English"
  title = "Badbaad"
  weight = 2
  [en.params]
    description = "Public health platform"

# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
